object: /Decomps/TOD-Decomp/ROMAssets/sys/main.dol
hash: 458a46afac46e2d94cf730e9132369db333eec59
symbols: \Decomps\TOD-Decomp/RawASM/DTKSymbolsNSplits/symbols.txt
splits: \Decomps\TOD-Decomp/RawASM/DTKSymbolsNSplits/splits.txt
